/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.arbolbinario;

/**
 *
 * @author SCIS2-13
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class ProductoGUI extends JFrame {
    private ArbolBinario arbol;

    public ProductoGUI() {
        arbol = new ArbolBinario();
        setTitle("Gestión de Productos");
        setSize(400, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // Panel de botones
        JPanel panelBotones = new JPanel();
        JButton btnInsertar = new JButton("Insertar Producto");
        JButton btnBuscar = new JButton("Buscar Similares");
        panelBotones.add(btnInsertar);
        panelBotones.add(btnBuscar);
        add(panelBotones, BorderLayout.NORTH);

        // Acciones de los botones
        btnInsertar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String color = JOptionPane.showInputDialog("Ingrese el color del producto:");
                String tamaño = JOptionPane.showInputDialog("Ingrese el tamaño del producto:");
                String marca = JOptionPane.showInputDialog("Ingrese la marca del producto:");

                if (color != null && tamaño != null && marca != null) {
                    Producto producto = new Producto(color, tamaño, marca);
                    boolean inserted = arbol.insertar(producto);
                    String mensaje = inserted ? "Producto insertado: " + marca : "No se pudo insertar el producto.";
                    JOptionPane.showMessageDialog(null, mensaje);
                }
            }
        });

        btnBuscar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String color = JOptionPane.showInputDialog("Ingrese el color del producto a buscar:");
                String tamaño = JOptionPane.showInputDialog("Ingrese el tamaño del producto a buscar:");
                String marca = JOptionPane.showInputDialog("Ingrese la marca del producto a buscar:");

                if (color != null && tamaño != null && marca != null) {
                    Producto buscado = new Producto(color, tamaño, marca);
                    List<Producto> similares = arbol.buscarSimilares(buscado);
                    StringBuilder mensaje = new StringBuilder("Productos similares encontrados: " + similares.size() + "\n");
                    for (Producto p : similares) {
                        mensaje.append(" - ").append(p.getMarca()).append(" (").append(p.getColor()).append(", ").append(p.getTamaño()).append(")\n");
                    }
                    JOptionPane.showMessageDialog(null, mensaje.toString());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
